import numpy as np
import pandas as pd
df=pd.read_csv('customers_100.csv')
print(df.head())
print(df.describe())
print(df.info())
print(df.isnull().sum())
print( df['age'].fillna(df['age'].mean(), inplace=True))
print(df.isnull().sum())
print(df['purchase_amount'].fillna(df['purchase_amount'].mean(), inplace=True))
print(df.isnull().sum())
print(df['name'].fillna('Unknown', inplace=True))
print(df.isnull().sum())
print(df)
print(df['name'].str.strip())
print(df['name'].str.title())
print(df['name'].str.replace(' ', ''))
print(df['name'].str.replace(' ', '').str.title())
print(df['name'].str.replace(' ', '').str.title().str.strip())
print(df['name'].str.replace(' ', '').str.title().str.strip().unique())
print(df.groupby('age')['name'].sum())