import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
df=pd.read_csv('customers_100.csv')
print(df.head())
print(df.describe())
print(df.info())
print(df.isnull().sum())
print( df['age'].fillna(df['age'].mean(), inplace=True))
print(df.isnull().sum())
print(df['purchase_amount'].fillna(df['purchase_amount'].mean(), inplace=True))
print(df.isnull().sum())
print(df['name'].fillna('Unknown', inplace=True))
print(df.isnull().sum())
print(df)
print(df.groupby('age')['purchase_amount'].mean())
print(df.sort_index())
print(df.sort_values(by='purchase_amount', ascending=False))
print(df[df['purchase_amount'] > 1000])
print(df[df['age'] < 30])
print(df['age'].mean())
print(df['purchase_amount'].mean())
print(df['age'].median())
print(df['purchase_amount'].median())

